name: 🧹 Code Quality Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff vulture

      - name: Run Black (format check)
        run: |
          black --check .

      - name: Run isort (import order check)
        run: |
          isort --check-only .

      - name: Run Ruff (lint + static analysis)
        run: |
          ruff check .

      - name: Run Vulture (dead code scan)
        run: |
          vulture . --min-confidence 70
